#!/bin/bash

# A SCRIPT TO COMPILE MY MATH HW lol!

cd /home/joshu/OneDrive/linux/school/math218/

if [ -z "$1" ]; then
	# Gets list of all set directories
	pset=$(ls -lav -x1 | tail -n 1)
else
	pset="$1"
fi

cd "$pset/src" || echo $pset/src Not Found || exit 1

if [ ! -d '../output' ]; then
	mkdir output
fi

items=$(ls *.xopp)

for i in $items; do
	echo $i
	name="${i%%.x*}"
	/snap/bin/xournalpp --create-pdf ../output/$name $i
done
