#!/bin/bash

# A SCRIPT TO COMPILE MY MATH HW lol!

cd /home/joshu/OneDrive/linux/school/math218/

if [ -z "$1" ]; then
	# Gets list of all set directories
	psets=$(ls -r -d set*/)
	# Gets latest set directory
	pset=${psets%%/*}
else
	pset="$1"
fi

cd "$pset/src" || echo $pset/src Not Found || exit 1

if [ ! -d '../output' ]; then
	mkdir output
fi

items=$(ls *.xopp)

for i in $items; do
	echo $i
	name="${i%%.x*}"
	xournalpp --create-pdf ../output/$name $i
done
