#!/bin/bash

cd /home/joshu/OneDrive/linux/school/math218/

psets=$(ls -r -d set*/)
pset=${psets%%/*}
num=${pset:3:1}
let "Next = $num + 1"

newDir="set$Next"
mkdir $newDir

cd $newDir

mkdir data gradescope output src
mkdir gradescope/notes
let "Left = 13 - $num"
echo "Set $Next directory created :). $Left more sets after this!"
