#!/bin/sh
source $(dirname $0)/.zshenv
if ! [ -d $ZPLUG_HOME ]; then
    echo "Installing zplug...."
    git clone https://github.com/zplug/zplug $ZPLUG_HOME
fi

function get_full_path {
    echo $(readlink -f $(dirname $0)/$1)
}

files=$(ls -ap $(get_full_path)| grep -v -E ".git*|/" | grep -E "^\.")
for dotfile in $files; do
    link_args="$(get_full_path)/$dotfile $HOME"
    ln -s $link_args
done

xdg_configs=$(ls $(get_full_path)/.config)
for dotfile in $xdg_configs; do
    link_args="$(get_full_path)/.config/$dotfile $HOME/.config/"
    ln -s $link_args
done

xdg_data=$(ls $(get_full_path)/.local/share)
for dotfile in $xdg_data; do
    link_args="$(get_full_path)/.local/share/$dotfile $HOME/.local/share"
    ln -s $link_args
done
