#!/bin/sh
#feh --no-fehbg --bg-scale "$HOME/.local/share/backgrounds/yuriTalesOfVesperia.png" 
#feh --no-fehbg --bg-scale "$HOME/.local/share/backgrounds/544f57.png"
feh --no-fehbg --bg-scale "$HOME/.local/share/backgrounds/leaf.png"
