#!/bin/env sh
source ~/.zshenv
get_time() {
    date -d "today + $1 minutes" +'%-H:%M'
}
fiften_minutes=$(get_time 15)
five_minutes=$(get_time 5)
now=$(get_time 0)

upcoming_times="$fiften_minutes|$five_minutes|$now"
print-agenda > /dev/null
awk_script='
{
    if ($2 ~ check_time) {
        split($0,time,/\.+|\s+/)
        split($0,a,":")
        print(time[3] a[4])
    }
}'

upcoming_events="$(cat ~/agenda | awk -v check_time=$upcoming_times "$awk_script") " 

# Variable is empty
if [ -z "${upcoming_events// }" ]
then
    exit 1
else
    CONKY_ENV="$upcoming_events" conky -c ~/.config/conky/print-env.conf -d
    xdo raise -N conky_env
    sleep 5
    pkill conky
fi

