#!/bin/env sh
upcoming_time=$(date -d "today + 15 minutes" +'%H:%M')
#upcoming_time="15:00"
print-agenda > /dev/null 2>&1 
awk_script='
{
    if ($2 ~ check_time) {
        split($0,a,":")
        print(check_time a[4])
    }
}'

upcoming_events="$(cat ~/agenda | awk -v check_time=$upcoming_time "$awk_script") " 

# Variable is empty
if [ -z "${upcoming_events// }" ]
then
    exit 1
else
    CONKY_ENV="$upcoming_events" conky -c ~/.config/conky/print-env.conf -d
    xdo raise -N conky_env
    sleep 5
    pkill conky
fi

