#!/bin/sh
for file in *.org; do
    emacs $file --batch -f org-md-export-to-markdown --kill
    filename=$(basename -- "$file")
    filename="${filename%.*}"
    mdfile="$filename.md"
    mdxfile="$filename.mdx"
    # Generates table of contents.. haha don't need for now generated with org
    #toc=$(cat $mdfile | grep -E "^#{1,5} " | sed -E 's/(#+) (.+)/\1~\2~\2/g' | awk -F "~" '{ gsub(/#/,"  ",$1); gsub(/[ ]/,"-",$3); print $1 "- [" $2 "](#" tolower($3) ")" }')
    echo "---" > "$mdxfile"
    awk -v RS='(\r?\n){2,}' '{print; exit}' $file | sed 's/#+//g' >> $mdxfile
    echo "---" >> "$mdxfile"
    #echo "$toc" >> "$mdxfile"
    cat "$filename.md" >> $mdxfile
    rm "$filename.md"

    emacs $file --batch -f org-latex-export-to-latex --kill
    pandoc --template eisvogel.latex -i "$filename.tex" -o "$filename.pdf"

done

# I got the TOC one liner from here: https://medium.com/@acrodriguez/one-liner-to-generate-a-markdown-toc-f5292112fd14
