#!/bin/env sh
current_time=$(date +'%H:%M')
upcoming=$(date -d "$current_time 15 minutes" +'%H:%M')
# TODO make print-agneda not open up the agneda in org haha
print-agenda > /dev/null 2>&1 

upcoming_event=$(cat ~/agenda | grep "$upcoming" | sed 's/-\+//' | sed 's/\.\+//' | awk '$1=$1')


# uf it's just a placeholder time or no time found at all
if [ "$upcoming_event" = "$upcoming" ] | [ "$upcoming_event" = "" ]
then
    exit 0
else
    upcoming_event=$(echo "$upcoming_event" | awk '{$1=$1}{$1= ""; print $0}')
    #echo "$upcoming_event"
    CONKY_ENV="$upcoming_event" conky -c ~/.config/conky/print-env.conf -d
    xdo raise -N conky_env
    sleep 5
    pkill conky
fi

