#!/bin/env sh

emacs_run () {
    echo $(emacsclient --eval "$1" 2> ~/.org-clock-polybar-err)
}

clocked_in=$(emacs_run '(org-clock-is-active)') 
icon="祥  "
if [ "$clocked_in" = "nil" ]
then
    icon="  "
fi

headline_time=$(emacs_run '(format "(%s) %s"  (org-minutes-to-clocksum-string (org-clock-get-clocked-time)) org-clock-heading)')
headline_time=$(echo ${headline_time:1:-1})

if [ "$headline_time" = "" ]
then
    headline_time="Nothing Clocked In"
    icon=""
fi

echo "$icon$headline_time"
