#!/bin/sh
PIXEL_ADD="60:B7:6E:30:72:42"

HEADPHONES_ADD="74:45:CE:46:CD:31"

BLUETOOTH_DEVICE="74:45:CE:46:CD:31"

if [[ $1 ]]; then
	case $1 in
		pixel) BLUETOOTH_DEVICE=$PIXEL_ADD;;
		whc) BLUETOOTH_DEVICE=$HEADPHONES_ADD;;
		*) echo 'WHATTTT IS THAT???'; exit 1;
	esac
fi

STATUS=$(bluetoothctl info $BLUETOOTH_DEVICE | grep Connected | cut -d ' ' -f2)

if [[ $STATUS == "yes" ]]; then
	bluetoothctl disconnect $BLUETOOTH_DEVICE
else
	bluetoothctl connect $BLUETOOTH_DEVICE
fi
